# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5851f00199d18d422233a6dc7ba0dd4e067e78a8202e4f81b341a127d35050d1fa6f502a8ab2c9ddd4218f889e05e11430d305262cdde8d251b3c5e35509f83
  domain_name: http://localhost:3001
  google_analytics_id: UA-43258479-2
  facebook_app_id: 1211927972190500
  facebook_app_secret: 2dcec11ca5cd72f1c9d9b433fda86a38
  linkedin_client_id: io4mas7jnhg0
  linkedin_client_secret: KA5bv37X4yW5yyVj
  google_client_id: 44076692204-9j255eoacru04figuoanho983g1q4sb6.apps.googleusercontent.com
  google_client_secret: u3zbuAee8LfBgtFnxAvpBIM3
  cloudinary_name: hireclub
  cloudinary_key: 443824319623561
  cloudinary_secret: fO4mkHzhIM8vaWZofR-tQ0ng7lE
  onesignal_app_id: 4e812b8e-0bac-4a3e-8794-9c162caa8b47
  onesignal_api_key: MWFjZmVmMGQtYzliZS00MWFjLThlYzctNGVlMGMzZDU1Mzcw

test:
  secret_key_base: 815330e7294365b7c08b28b07aa8725012c83ae9be9712d5f60c23512653c929321bc7c67c0b7088d597870759e035a225d334654c539edb42c4aa4102bd9a5f
  domain_name: http://localhost:3001
  google_analytics_id: UA-43258479-2
  facebook_app_id: 1211927972190500
  facebook_app_secret: 2dcec11ca5cd72f1c9d9b433fda86a38
  onesignal_app_id: 4e812b8e-0bac-4a3e-8794-9c162caa8b47
  onesignal_api_key: MWFjZmVmMGQtYzliZS00MWFjLThlYzctNGVlMGMzZDU1Mzcw

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  google_analytics_id: <%= ENV["GOOGLE_ANALYTICS_ID"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  linkedin_client_id: <%= ENV["LINKEDIN_CLIENT_ID"] %>
  linkedin_client_secret: <%= ENV["LINKEDIN_CLIENT_SECRET"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  asset_host: <%= ENV["ASSET_HOST"] %>
  cloudinary_name: <%= ENV["CLOUDINARY_NAME"] %>
  cloudinary_key: <%= ENV["CLOUDINARY_KEY"] %>
  cloudinary_secret: <%= ENV["CLOUDINARY_SECRET"] %>
  onesignal_app_id: <%= ENV["ONESIGNAL_APP_ID"] %>
  onesignal_api_key: <%= ENV["ONESIGNAL_API_KEY"] %>
