$(document).ready ->
  companySearch = (query, syncResults, asyncResults) ->
    $.get '/companies.json', { query: query }, ((data) ->
      asyncResults data
      return
    ), 'json'
    return

  $('input#milestone_company').typeahead {
    minLength: 1
    hint: false
    highlight: true
  },
    name: 'company-search-results'
    source: companySearch
    display: (company) ->
      company.name
  # company selected, let's set hidden company_id field
  $('input#milestone_company').bind 'typeahead:select', (ev, company) ->
    # Set hidden form field of company_id
    $('input#milestone_company_id').val company.id
    return
  return

# ---
# generated by js2coffee 2.2.0