$(document).ready ->
  skillSearch = (query, syncResults, asyncResults) ->
    $.get '/skills.json', { query: query }, ((data) ->
      asyncResults data
      return
    ), 'json'
    return

  $('input#user_skill_skill').typeahead {
    minLength: 0
    hint: false
    highlight: true
  },
    name: 'skill-search-results'
    source: skillSearch
    display: (skill) ->
      skill.name
  # skill selected, let's set hidden skill_id field
  $('input#user_skill_skill').bind 'typeahead:select', (ev, skill) ->
    # Set hidden form field of skill_id
    $('input#user_skill_skill_id').val skill.id
    return
  return

# ---
# generated by js2coffee 2.2.0