console.log 'autocomplete_location'
$(document).ready ->
  console.log 'ready'

  locationSearch = (query, syncResults, asyncResults) ->
    $.get '/locations.json', { query: query }, ((data) ->
      console.log query
      asyncResults data
      return
    ), 'json'
    return

  $('input#user_location').typeahead {
    minLength: 1
    hint: false
    highlight: true
  },
    name: 'location-search-results'
    source: locationSearch
    display: (location) ->
      location.display_name
  # location selected, let's set hidden location_id field
  $('input#user_location').bind 'typeahead:select', (ev, location) ->
    # Set hidden form field of location_id
    console.log location
    $('input#user_location_id').val location.id
    return
  return

# ---
# generated by js2coffee 2.2.0