$(document).ready ->
  companySearch = (query, syncResults, asyncResults) ->
    $.get '/companies.json', { query: query }, ((data) ->
      asyncResults data
      return
    ), 'json'
    return

  $('.autocomplete_company').typeahead {
    minLength: 1
    hint: false
    highlight: true
  },
    name: 'autocomplete_company'
    source: companySearch
    display: (company) ->
      company.name
    templates:
      empty: 'not found'
      suggestion: (el) ->
        '<div>' + '<img class="mr-2 rounded" width="50" src="' + el.avatar_url + '" />' + '<strong>' + el.name + '</strong> ' + '</div>'
  # company selected, let's set hidden company_id field
  $('.autocomplete_company').bind 'typeahead:select', (ev, company) ->
    # Set hidden form field of company_id
    console.log("select")
    $('.autocomplete_company_id').val company.id
    return
  $('.autocomplete_company').bind 'blur', (ev) ->
    # clear company id if no value
    console.log("close")
    if ev.target.value == ""
        console.log("clear value")
        $('.autocomplete_company_id').val ""
  return

# ---
# generated by js2coffee 2.2.0
