$(document).ready ->
  $('#new_message').formValidation(
    framework: 'bootstrap4'
    icon:
      valid: 'fa fa-check'
      invalid: 'fa fa-times'
      validating: 'fa fa-refresh'
    fields:
      'message[text]':
        validators:
          notEmpty: 
            message: ''


  )

  return

# ---
# generated by js2coffee 2.2.0
